// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Scoreboard.Website.Data;

namespace Scoreboard.Website.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("USSEScoreboard.Models.Highlight", b =>
                {
                    b.Property<int>("HighlightId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateEnd");

                    b.Property<DateTime>("DateModified");

                    b.Property<DateTime>("DateStart");

                    b.Property<int>("UserProfileId");

                    b.HasKey("HighlightId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Highlight");
                });

            modelBuilder.Entity("USSEScoreboard.Models.UserProfile", b =>
                {
                    b.Property<int>("UserProfileId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateModified");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100);

                    b.Property<string>("FirstName")
                        .HasMaxLength(100);

                    b.Property<bool>("IsActiveTeamMember");

                    b.Property<bool>("IsAscendNotes");

                    b.Property<bool>("IsCRM");

                    b.Property<bool>("IsExpenses");

                    b.Property<bool>("IsFRI");

                    b.Property<string>("LastName")
                        .HasMaxLength(100);

                    b.Property<int>("TotalAscend");

                    b.Property<int>("TotalPresentations");

                    b.Property<string>("UserId")
                        .HasMaxLength(450);

                    b.HasKey("UserProfileId");

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("USSEScoreboard.Models.Highlight", b =>
                {
                    b.HasOne("USSEScoreboard.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
